spring:
  application:
    name:
      WishList
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl: false
#      generate-ddl: true
#      ddl-auto: update
    show-sql: true
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    url: jdbc:h2:file:~/test2;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
#    driverClassName: org.h2.Driver


#server:
#  port: 8081

#logging:
#  level:
#    org:
#      springframework: TRACE


